name: winemag
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - tornado=5.1.1
  - jupyterlab=0.35.*
  - widgetsnbextension=3.4*
  - ipywidgets=7.4.*
  - matplotlib=3.*
  - numpy=1.*
  - pandas=0.24.*
  - pip:
    - Scrapy>=1.6
    - scrapy-fake-useragent>=1.1
